version: "2"

services:
  django:
    build:
      context: .
    container_name: django
    depends_on:
      - pgdb
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - net

  nuxt:
    build:
      context: ./frontend/
    container_name: nuxt
    depends_on:
      - django
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - net
    command: >
      bash -c "npm run dev"
  pgdb:
    image: postgres:15
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - net
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - django
      - nuxt
    networks:
      - net
networks:
  net:
    name: net
    external: true

volumes:
  static_volume:
  media_volume:
  pgdbdata:

