version: "2"

services:
  watch_project:
    image: watch_project:latest
    container_name: watch_project
    depends_on:
      - pgdb
    ports:
      - "8000:8000"
    command: >
      bash -c "python3 manage.py runserver 0.0.0.0:8000"
  frontend_watch:
    image: frontend_watch:latest
    container_name: frontend_watch
    ports:
      - "3000:3000"
    command: >
      bash -c "npm run dev"
  pgdb:
    image: postgres:15
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    env_file:
      - .env
volumes:
  static_volume:
  media_volume:
  pgdbdata: