# Generated by Django 5.0.1 on 2025-02-11 05:36

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='News text')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of creation')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('likes', models.ManyToManyField(blank=True, related_name='news_like', to=settings.AUTH_USER_MODEL, verbose_name='Likes')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comment text')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of creation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_news', to='blog.news', verbose_name='News')),
            ],
        ),
    ]
